### PR TITLE
Docker/entrypoint: support disk mounting in service container

### PR DESCRIPTION
**Pull request by legionxiong**
### What problem does this PR solve?

Issue Number: #2283 

Problem Summary:

### What is changed and how it works?

What's Changed:  docker/debian9/entrypoint.sh

How it Works:  disk device will be mounted by entrypoint.sh if --disk parameter was injected when deploy curvebs.

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by ilixiaocui** [comment]
@caoxianfei1 why pending?

**Comment by Cyber-SiKu** [comment]
@legionxiong Please merge into master first

**Comment by legionxiong** [comment]
> 

The pull request of this patch for `master` is https://github.com/opencurve/curve/pull/2285.

**Comment by Cyber-SiKu** [comment]
@legionxiong Please merge into master first.

**Pull request closed without merging**
