### PR TITLE
[tool-v2] fix: get copyset status from braft metric on chunkserver

### PR DESCRIPTION
**Pull request by caoxianfei1**
### What problem does this PR solve?

When executing status copyset, avoid querying the copyset one by one, but directly query the draft metric.

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Review by Cyber-SiKu — APPROVED** [review]

**Review by wu-hanqing — APPROVED** [review]

**Pull request merged**
