### PR TITLE
[feat]tools-v2: add snapshot utils

### PR DESCRIPTION
**Pull request by baytan0720**
### What problem does this PR solve?

too much snapshot const and functions are private

Issue Number: #xxx 

Problem Summary:

public snapshot const and functions in internal/utils/snapshot.go

### What is changed and how it works?

What's Changed:

create tools-v2/internal/utils/snapshot.go
move and modify tools-v2/pkg/cli/command/curvebs/delete/volume/clone.go to tools-v2/pkg/cli/command/curvebs/delete/volume/clone/clone.go
move and modify tools-v2/pkg/cli/command/curvebs/delete/volume/recover.go to tools-v2/pkg/cli/command/curvebs/delete/volume/recover/recover.go
delete tools-v2/pkg/cli/command/curvebs/delete/volume/clone_or_recover.go

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by baytan0720** [comment]
cicheck

**Comment by baytan0720** [comment]
cicheck

**Comment by baytan0720** [comment]
cicheck

**Review by Cyber-SiKu — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by baytan0720** [comment]
cicheck

**Review by caoxianfei1 — APPROVED** [review]

**Pull request merged**
