### PR TITLE
curvefs/client: limited download retry times

### PR DESCRIPTION
**Pull request by CodeFarmerPK**
Signed-off-by: CodeFarmerPK <CodeFarmer.PK@Gmail.com>

### What problem does this PR solve?

Issue Number: #2020 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by CodeFarmerPK** [comment]
recheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by wuhongsong** [comment]
cicheck

**Comment by wuhongsong** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by CodeFarmerPK** [comment]
cicheck

**Comment by wuhongsong** [comment]
cicheck

**Review by wuhongsong — APPROVED** [review]

**Review by cw123 — APPROVED** [review]

**Pull request merged**
