### PR TITLE
Curve/tool fs status metaserver

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

```
curve fs status metaserver
+--------------------+--------------------+----------------+--------+
|    externalAddr    |    internalAddr    |    version     | status |
+--------------------+--------------------+----------------+--------+
| 10.219.192.50:6800 | 10.219.192.50:6800 | 6de073a7+debug | online |
| 10.219.192.50:6802 | 10.219.192.50:6802 | 6de073a7+debug | online |
| 10.219.192.50:6801 | 10.219.192.50:6801 | 6de073a7+debug | online |
+--------------------+--------------------+----------------+--------+
curve fs status metaserver --format json
{
"error": {
"code": 0,
"message": "success"
},
"result": [
{
"externalAddr": "10.219.192.50:6800",
"internalAddr": "10.219.192.50:6800",
"status": "online",
"version": "6de073a7+debug"
},
{
"externalAddr": "10.219.192.50:6802",
"internalAddr": "10.219.192.50:6802",
"status": "online",
"version": "6de073a7+debug"
},
{
"externalAddr": "10.219.192.50:6801",
"internalAddr": "10.219.192.50:6801",
"status": "online",
"version": "6de073a7+debug"
}
]
}
```

image
image

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by aspirer** [comment]
add dummy server to list output?

**Comment by Cyber-SiKu** [comment]
> add dummy server to list output?

Use externalAddr and internalAddr instead of addr

**Review by wu-hanqing — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Pull request merged**
