### PR TITLE
mds/metaserver: Add idle_timeout_sec option

### PR DESCRIPTION
**Pull request by 201341**
### What problem does this PR solve?
Add idle_timeout_sec option to reduce server resource

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by 201341** [comment]
cicheck

**Comment by wuhongsong** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Review by ilixiaocui — DISMISSED** [review]

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
mds election timeout, it's very strange

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by Ziy1-Tan** [comment]
> mds election timeout, it's very strange

same as https://github.com/opencurve/curve/pull/2501. Do you have any idea? @ilixiaocui @201341

**Comment by ilixiaocui** [comment]
> > mds election timeout, it's very strange
> 
> same as #2501. Do you have any idea? @ilixiaocui @201341

Can you take a screenshot of the failure message?

**Comment by ilixiaocui** [comment]
This pr involves the management of link methods, and it is necessary to actually test the scope of influence.

**Comment by Ziy1-Tan** [comment]
> > > mds election timeout, it's very strange
> > 
> > 
> > same as #2501. Do you have any idea? @ilixiaocui @201341
> 
> Can you take a screenshot of the failure message?

image

**Comment by ilixiaocui** [comment]
cicheck

**Comment by SeanHai** [comment]
cicheck

**Comment by wuhongsong** [comment]
> > > > mds election timeout, it's very strange
> > > 
> > > 
> > > same as #2501. Do you have any idea? @ilixiaocui @201341
> > 
> > 
> > Can you take a screenshot of the failure message?
> 
> image

@SeanHai  help

**Comment by SeanHai** [comment]
F 2023-06-19T15:46:11.641566+0800     6 configuration.cpp:300] Get mds.server.idleTimeoutSec from /curvefs/mds/conf/mds.conf fail
*** Check failure stack trace: ***
*** Aborted at 1687160771 (unix time) try "date -d @1687160771" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x6) received by PID 6 (TID 0x7f94b5fcc4c0) from PID 6; stack trace: ***
    @     0x7f94b400d0e0 (unknown)
    @     0x7f94b26c4fff gsignal
    @     0x7f94b26c642a abort
    @     0x55dcdc40492c google::FlushAndAbort()
    @     0x55dcdc401b7e google::LogMessage::Fail()
    @     0x55dcdc401ac7 google::LogMessage::SendToLog()
    @     0x55dcdc4012f0 google::LogMessage::Flush()
    @     0x55dcdc4042c0 google::LogMessageFatal::~LogMessageFatal()
    @     0x55dcdbf59410 curve::common::Configuration::GetValueFatalIfFail()
    @     0x55dcdb739b75 curvefs::mds::MDS::InitOptions()
    @     0x55dcdb73740e main
    @     0x7f94b26b22e1 __libc_start_main
    @     0x55dcdb736c6a _start
    @                0x0 (unknown)

The name in conf is 'mds.server.idleTimeOutSec', but you get in code is 'mds.server.idleTimeoutSec'.  Please fix it and retry.

**Comment by 201341** [comment]
cicheck

**Comment by wuhongsong** [comment]
i will have a test this days.

**Comment by 201341** [comment]
cicheck

**Comment by wuhongsong** [comment]
`Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ` , ci failed because of network

**Comment by wuhongsong** [comment]
cicheck

**Comment by wuhongsong** [comment]
> i will have a test this days.
I have done tests, including functional tests and performance verification, and they are as expected

**Review by wuhongsong — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]

**Pull request merged**
