### PR TITLE
reserve inode id from 0~1000

### PR DESCRIPTION
**Pull request by cw123**
Signed-off-by: chenwei <461432360@qq.com>

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by cw123** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by cw123** [comment]
新创建的partition使用新的规则，从1001开始分配inode，旧的patition分配inode的规则不变。
The new partition assigns inode id from 1001. The rules for assigning inode ids to the old partition remain unchanged
why?
如果旧的partition分配了几个inode，然后修改规则变成从1001开始分配，如果这些inode分配没有打快照，那么在从旧版本向新版本升级的时候，metaserver服务重启的时候，创建inode的请求就会从raft log中重放，原本申请的[2,1000]的inodeid，重放的时候就变成了[1001, 1999]，系统中的inode id就不匹配，会导致一些dentry记录的inode有问题。
If the old partition allocates several inodes, and then modify the rules to start allocation from 1001, if these inode allocations are not snapshotted, then when upgrading from the old version to the new version, when the metaserver service restarts, a request to create an inode It will be replayed from the raft log. The inodeid of [2,1000] originally applied for will become [1001, 1999] when replayed. The inode id in the system will not match, which will lead to some inode records recorded by dentry. something wrong.

node21:~/cwdir1$ for i in {1..20}; do mkdir dir$i;done
node21:~/cwdir1$ for i in {1..20}; do touch dir$i/file$i;done
node21:~/cwdir1$ for i in {1..20}; do stat dir$i/file$i | grep -E "File|Device";done
  File: dir1/file1
Device: 53h/83d Inode: 4194304     Links: 1
  File: dir2/file2
Device: 53h/83d Inode: 11534337    Links: 1
  File: dir3/file3
Device: 53h/83d Inode: 10485763    Links: 1
  File: dir4/file4
Device: 53h/83d Inode: 9437186     Links: 1
  File: dir5/file5
Device: 53h/83d Inode: 7340032     Links: 1
  File: dir6/file6
Device: 53h/83d Inode: 2097155     Links: 1
  File: dir7/file7
Device: 53h/83d Inode: 1048577     Links: 1
  File: dir8/file8
Device: 53h/83d Inode: 3           Links: 1
  File: dir9/file9
Device: 53h/83d Inode: 7340033     Links: 1
  File: dir10/file10
Device: 53h/83d Inode: 8388609     Links: 1
  File: dir11/file11
Device: 53h/83d Inode: 3145731     Links: 1
  File: dir12/file12
Device: 53h/83d Inode: 5242883     Links: 1
  File: dir13/file13
Device: 53h/83d Inode: 4           Links: 1
  File: dir14/file14
Device: 53h/83d Inode: 6291458     Links: 1
  File: dir15/file15
Device: 53h/83d Inode: 5           Links: 1
  File: dir16/file16
Device: 53h/83d Inode: 5242884     Links: 1
  File: dir17/file17
Device: 53h/83d Inode: 6291459     Links: 1
  File: dir18/file18
Device: 53h/83d Inode: 7340034     Links: 1
  File: dir19/file19
Device: 53h/83d Inode: 2097156     Links: 1
  File: dir20/file20
Device: 53h/83d Inode: 1048578     Links: 1


node21:~/cwdir1$ for i in {1..20}; do stat dir$i/file$i | grep -E "File|Device";done
  File: dir1/file1
Device: 53h/83d Inode: 4194304     Links: 1
  File: dir2/file2
Device: 53h/83d Inode: 11534337    Links: 1
  File: dir3/file3
Device: 53h/83d Inode: 10485763    Links: 1
  File: dir4/file4
Device: 53h/83d Inode: 9437186     Links: 1
  File: dir5/file5
Device: 53h/83d Inode: 7340032     Links: 1
  File: dir6/file6
Device: 53h/83d Inode: 2097155     Links: 1
stat: cannot stat 'dir7/file7': No such file or directory
stat: cannot stat 'dir8/file8': No such file or directory
  File: dir9/file9
Device: 53h/83d Inode: 7340033     Links: 1
  File: dir10/file10
Device: 53h/83d Inode: 8388609     Links: 1
  File: dir11/file11
Device: 53h/83d Inode: 3145731     Links: 1
  File: dir12/file12
Device: 53h/83d Inode: 5242883     Links: 1
stat: cannot stat 'dir13/file13': No such file or directory
  File: dir14/file14
Device: 53h/83d Inode: 6291458     Links: 1
stat: cannot stat 'dir15/file15': No such file or directory
  File: dir16/file16
Device: 53h/83d Inode: 5242884     Links: 1
  File: dir17/file17
Device: 53h/83d Inode: 6291459     Links: 1
  File: dir18/file18
Device: 53h/83d Inode: 7340034     Links: 1
  File: dir19/file19
Device: 53h/83d Inode: 2097156     Links: 1
  File: dir20/file20
Device: 53h/83d Inode: 1048578     Links: 1

**Comment by leonrayang** [comment]
Hi cw123, can you show which version from and to which version to upgrade, tks

**Pull request closed without merging**
