### PR TITLE
[feat]tools-v2: curve bs create clone

### PR DESCRIPTION
**Pull request by lng2020**
### What problem does this PR solve?

Issue Number: #2586  

Problem Summary: add `curve bs create clone` command

### What is changed and how it works?

What's Changed: ./pkg/cli/command/curvebs/create/create.go, ./pkg/cli/command/curvebs/create/clone and ./pkg/internal/error/error.go

How it Works:  send `CreateCloneFileRequest` to clone file

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by Cyber-SiKu — COMMENTED** [review]
The command should be two:
```bash
curve bs create volume clone
curve bs create volume recover
```
They all use the same rpc request, but the parameters are not available.
You can abstract this rpc request, and then call it separately by the above commands. For this, you can refer to create file/dir.

**Review by Cyber-SiKu — COMMENTED** [review]
You can add instructions on how to use it in the readme.

**Comment by lng2020** [comment]
will do

**Comment by Cyber-SiKu** [comment]
@lng2020 continue？

**Comment by wuhongsong** [comment]
@lng2020   any trouble?

**Comment by Cyber-SiKu** [comment]
> > 
> 
> wait for #2713 to merge. Those commands are highly associated, with basically the exact solutions.

merged

**Review by Cyber-SiKu — COMMENTED** [review]
add some output

**Comment by caoxianfei1** [comment]
@lng2020 continue?

**Comment by lng2020** [comment]
> @lng2020 continue?

No. Sorry about that. But it's almost finished. Maybe others can refer this.

**Pull request closed without merging**
