### PR TITLE
curvefs/client: move fork to the front of InitGlog and InitFuseClient

### PR DESCRIPTION
**Pull request by h0hmj**
### What problem does this PR solve?

Issue Number: #1414 

Problem Summary:

client deadlock after fork

### What is changed and how it works?

What's Changed:

How it Works:

move fork to the front of InitGlog and InitFuseClient

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by h0hmj** [comment]
recheck

**Comment by h0hmj** [comment]
recheck

**Comment by h0hmj** [comment]
recheck

**Comment by h0hmj** [comment]
fix umount crash when diskcache=disable

when diskcache=disable, bgFlushThread_ will not be start.
it is not joinable.

**Review by wu-hanqing — APPROVED** [review]

**Review by SeanHai — APPROVED** [review]

**Pull request merged**
