### PR TITLE
flaky bs ci

### PR DESCRIPTION
**Pull request by fansehep**
Signed-off-by: fan <yfan3763@gmail.com>

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by fansehep** [comment]
cc @wu-hanqing  should fix it?

**Comment by wu-hanqing** [comment]
cc @ilixiaocui

**Comment by ilixiaocui** [comment]
This is really a headache :(. Can you comment out this judgment on time?

**Comment by fansehep** [comment]
> This is really a headache :(. Can you comment out this judgment on time?

quote an old saying:
子贡问为仁，子曰：“工欲善其事，必先利其器。居是邦也，事其大夫之贤者，友其士之仁者。”
We all use CI, but he's not doing well. ```recheck``` sure it can solve the problem. But time is precious and patience is limited. I am tired for this. As a community member, i love being able to examine this issue, both for myself and for others.

**Comment by ilixiaocui** [comment]
> > This is really a headache :(. Can you comment out this judgment on time?
> 
> quote an old saying: 子贡问为仁，子曰：“工欲善其事，必先利其器。居是邦也，事其大夫之贤者，友其士之仁者。” We all use CI, but he's not doing well. `recheck` sure it can solve the problem. But time is precious and patience is limited. I am tired for this. As a community member, i love being able to examine this issue, both for myself and for others.

Thanks for your suggestion, we will improve it later！

**Comment by fansehep** [comment]
> > > This is really a headache :(. Can you comment out this judgment on time?
> > 
> > 
> > quote an old saying: 子贡问为仁，子曰：“工欲善其事，必先利其器。居是邦也，事其大夫之贤者，友其士之仁者。” We all use CI, but he's not doing well. `recheck` sure it can solve the problem. But time is precious and patience is limited. I am tired for this. As a community member, i love being able to examine this issue, both for myself and for others.
> 
> Thanks for your suggestion, we will improve it later！

hope as soon as possible.

**Comment by ilixiaocui** [comment]
tested by #2168

**Pull request closed without merging**
