### PR TITLE
curvefs/client: fix memory usage is so high.

### PR DESCRIPTION
**Pull request by Wine93**

### CODE REVIEW

**Comment by Wine93** [comment]
cicheck

**Comment by Wine93** [comment]
cicheck

**Comment by Wine93** [comment]
cicheck

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by Wine93** [comment]
cicheck

**Comment by caoxianfei1** [comment]
@Wine93 fixed? Can it be closed?

**Pull request closed without merging**
