### PR TITLE
curvefs metaserver : update inode avoid copying

### LINKED ISSUE #960: GetDentry and AppendS3chunkInfo timeout
**Describe the bug (描述bug)**
image

Secret Key: ItNZntrnWDFOumRZkbcY429Kbd3VXQB1
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by xu-chaojie**
### What problem does this PR solve?

Issue Number: close #960  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Review by cw123 — APPROVED** [review]

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Pull request merged**
