### PR TITLE
client: disable cto

### PR DESCRIPTION
**Pull request by ilixiaocui**
…nts"

This reverts commit c933bb67e4475ea980d695994263fb580c5baaa6.

### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by xu-chaojie — APPROVED** [review]

**Review by baijiaruo — APPROVED** [review]

**Comment by ilixiaocui** [comment]
recheck

**Comment by ilixiaocui** [comment]
recheck

**Comment by ilixiaocui** [comment]
recheck

**Comment by ilixiaocui** [comment]
abandoned

**Pull request closed without merging**
