### PR TITLE
add create volume cli

### PR DESCRIPTION
**Pull request by wangyanghack**
### What problem does this PR solve?

Issue Number: #2031 

image

### CODE REVIEW

**Comment by caoxianfei1** [comment]
@wangyanghack keep on?

**Comment by ilixiaocui** [comment]
@wangyanghack Is the PR still going on? If it is done, please cicheck first to ensure that ci passes.

**Comment by caoxianfei1** [comment]
@wangyanghack there is a conflicts,  you can fix it and retry ci.

**Comment by wuhongsong** [comment]
need rebase

**Comment by Cyber-SiKu** [comment]
@wangyanghack I implemented pr#2404 based on your code, you can refer to it for modification.

**Comment by aspirer** [comment]
#2404

**Pull request closed without merging**
