### PR TITLE
curvefs/client: fix two coredump problems

### PR DESCRIPTION
**Pull request by wu-hanqing**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by YunhuiChen** [comment]
datacheck

**Comment by opencurveadmin** [comment]
Can one of the admins verify this patch?

**Comment by YunhuiChen** [comment]
datacheck

**Comment by wu-hanqing** [comment]
recheck

**Comment by wu-hanqing** [comment]
recheck

**Review by baijiaruo — APPROVED** [review]

**Comment by wu-hanqing** [comment]
recheck

**Comment by wu-hanqing** [comment]
recheck

**Review by ilixiaocui — APPROVED** [review]

**Pull request merged**
