### PR TITLE
fix_mds_mem_leak

### PR DESCRIPTION
**Pull request by cw123**
### What problem does this PR solve?

Problem Summary: fix mds mem leak in etcd client

### What is changed and how it works?

What's Changed: fix mds mem leak in etcd client

How it Works: fix mds mem leak in etcd client

Side effects(Breaking backward compatibility? Performance regression?):  no

need urgent bug fix

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by aspirer** [comment]
pls use English

**Review by aspirer — COMMENTED** [review]
fix_mds_mem_leak --> fix mds mem leak in etcd client？

**Comment by cw123** [comment]
> pls use English

OK

**Comment by cw123** [comment]
> fix_mds_mem_leak --> fix mds mem leak in etcd client？

done

**Comment by aspirer** [comment]
> > fix_mds_mem_leak --> fix mds mem leak in etcd client？
> 
> done
I mean change commit message to "fix mds mem leak in etcd client".

**Review by ilixiaocui — APPROVED** [review]

**Comment by cw123** [comment]
> > > fix_mds_mem_leak --> fix mds mem leak in etcd client？
> > 
> > 
> > done
> 
> I mean change commit message to "fix mds mem leak in etcd client".

done

**Review by bai-charisu — APPROVED** [review]

**Comment by cw123** [comment]
bug fix cherry-pick from master

**Pull request merged**
