### PR TITLE
[feat] CurveBS: delete apply index in client

### PR DESCRIPTION
**Pull request by Xinlong-Chen**
### What problem does this PR solve?

Issue Number: #1598

Problem Summary: delete apply index in client

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by Xinlong-Chen** [comment]
@ilixiaocui @wu-hanqing PTAL～

**Review by ilixiaocui — APPROVED** [review]

**Pull request merged**
