### PR TITLE
revert new s3 sdk due to critical bug

### PR DESCRIPTION
**Pull request by h0hmj**
### What problem does this PR solve?

s3 sdk hang

### What is changed and how it works?

What's Changed:

revert new s3 sdk due to critical bug @wuhongsong

### CODE REVIEW

**Comment by h0hmj** [comment]
critical bug was reported by @wuhongsong

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
cicheck

**Review by wuhongsong — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]

**Comment by wuhongsong** [comment]
image

It's an unsolved bug in aws(https://github.com/aws/aws-sdk-cpp/issues/2111)

and the new aws sdk is not stable now. There are some serious bugs
image

**Pull request merged**
