### PR TITLE
metaserver: let copyset visible after started

### PR DESCRIPTION
**Pull request by wu-hanqing**
### What problem does this PR solve?

Issue Number: #1790

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by wu-hanqing** [comment]
recheck

**Comment by ilixiaocui** [comment]
cc @wu-hanqing Please resubmit the pr to the new master branch.

**Comment by ilixiaocui** [comment]
cc @wu-hanqing Does this PR still need to be added?

**Comment by wuhongsong** [comment]
@wu-hanqing

**Comment by caoxianfei1** [comment]
@wu-hanqing still keep on?

**Comment by wu-hanqing** [comment]
> @wu-hanqing still keep on?

I will finish it as soon as possible.

**Pull request closed without merging**
