### PR TITLE
add .bazelversion

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

use bazelisk $ file .bazelversion to use bazel in specified version

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Cyber-SiKu** [comment]
recheck

**Review by wu-hanqing — APPROVED** [review]

**Review by SeanHai — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Pull request merged**
