### PR TITLE
[compile] update the braft to vesion v1.1.2

### PR DESCRIPTION
**Pull request by tangwz**
Signed-off-by: tangwz <tangwz.com@gmail.com>

### What problem does this PR solve?

Issue Number: #2071 

Problem Summary:

Update braft to latest version v1.1.2

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by tangwz** [comment]
@ilixiaocui @wu-hanqing  CI use the repo https://gitee.com/baidu/braft, but this repo hasn't sync the newest version from https://github.com/baidu/braft/releases/tag/v1.1.2.So do we use version v1.1.1?

**Comment by wu-hanqing** [comment]
> @ilixiaocui @wu-hanqing CI use the repo https://gitee.com/baidu/braft, but this repo hasn't sync the newest version from https://github.com/baidu/braft/releases/tag/v1.1.2.So do we use version v1.1.1?

@zhanghuidinah Please clone [braft](https://github.com/baidu/braft) under https://gitee.com/NetEase_Curve and ensure tag v1.1.2 exists.

**Comment by zhanghuidinah** [comment]
https://gitee.com/NetEase_Curve/braft/tree/v1.1.2/  @tangwz PTAL

**Comment by tangwz** [comment]
> https://gitee.com/NetEase_Curve/braft/tree/v1.1.2/ @tangwz PTAL

It's a private repo?

**Comment by wu-hanqing** [comment]
> > https://gitee.com/NetEase_Curve/braft/tree/v1.1.2/ @tangwz PTAL
> 
> @zhanghuidinah It's a private repo?I have no permission.

Sorry, it's a mistake. It's a public repository now.

**Comment by cw123** [comment]
recheck

**Comment by cw123** [comment]
recheck

**Comment by ilixiaocui** [comment]
Please synthesize a commit to submit.

**Review by ilixiaocui — APPROVED** [review]

**Comment by ilixiaocui** [comment]
LGTM！

**Review by wu-hanqing — APPROVED** [review]

**Pull request merged**
