### PR TITLE
Curve/tool fs list fs

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

list fs

list mountpoint

How it Works:

```
curve fs list fs
curve fs list fs
+-----+-------+--------+--------------+-----------+---------+----------+-----------+----------+
| id  | name  | status |   capacity   | blockSize | fsType  | sumInDir |   owner   | mountNum |
+-----+-------+--------+--------------+-----------+---------+----------+-----------+----------+
| 102 | test4 | INITED | 107374182400 |  1048576  | TYPE_S3 |  false   | anonymous |    1     |
| 101 | test3 | INITED | 107374182400 |  1048576  | TYPE_S3 |  false   | anonymous |    1     |
|  1  | test1 | INITED | 107374182400 |  1048576  | TYPE_S3 |  false   | anonymous |    3     |
+-----+-------+--------+--------------+-----------+---------+----------+-----------+----------+

curve fs list fs --format json                         

{
"error": {
"code": 0,
"message": "success"
},
"result": {
"fsInfo": [
{
"blockSize": "1048576",
"capacity": "107374182400",
"detail": {
"s3Info": {
"ak": "minioadmin",
"blockSize": "4194304",
"bucketname": "test",
"chunkSize": "67108864",
"endpoint": "http://172.17.0.2:9000",
"sk": "minioadmin"
}
},
"enableSumInDir": false,
"fsId": 102,
"fsName": "test4",
"fsType": "TYPE_S3",
"mountNum": 1,
"mountpoints": [
{
"hostname": "siku-QiTianM420-N000",
"path": "/curvefs/client/mnt/home/siku/temp/mnt4",
"port": 9005
}
],
"owner": "anonymous",
"rootInodeId": "1",
"status": "INITED",
"txOwner": "",
"txSequence": "0"
},
{
"blockSize": "1048576",
"capacity": "107374182400",
"detail": {
"s3Info": {
"ak": "minioadmin",
"blockSize": "4194304",
"bucketname": "test",
"chunkSize": "67108864",
"endpoint": "http://172.17.0.2:9000",
"sk": "minioadmin"
}
},
"enableSumInDir": false,
"fsId": 101,
"fsName": "test3",
"fsType": "TYPE_S3",
"mountNum": 1,
"mountpoints": [
{
"hostname": "siku-QiTianM420-N000",
"path": "/curvefs/client/mnt/home/siku/temp/mnt3",
"port": 9004
}
],
"owner": "anonymous",
"rootInodeId": "1",
"status": "INITED",
"txOwner": "",
"txSequence": "0"
},
{
"blockSize": "1048576",
"capacity": "107374182400",
"detail": {
"s3Info": {
"ak": "minioadmin",
"blockSize": "4194304",
"bucketname": "test",
"chunkSize": "67108864",
"endpoint": "http://172.17.0.2:9000",
"sk": "minioadmin"
}
},
"enableSumInDir": false,
"fsId": 1,
"fsName": "test1",
"fsType": "TYPE_S3",
"mountNum": 3,
"mountpoints": [
{
"hostname": "siku-QiTianM420-N000",
"path": "/curvefs/client/mnt/home/siku/temp/mnt1",
"port": 9002
},
{
"hostname": "siku-QiTianM420-N000",
"path": "/curvefs/client/mnt/home/siku/temp/mnt2",
"port": 9003
},
{
"hostname": "siku-QiTianM420-N000",
"path": "/curvefs/client/mnt/home/siku/temp/mnt5",
"port": 9006
}
],
"owner": "anonymous",
"rootInodeId": "1",
"status": "INITED",
"txOwner": "",
"txSequence": "0"
}
]
}
}

curve fs list mountpoint
+-------+---------+-------------------------------------------------------------------+
| fs id | fs name |                            mount point                            |
+-------+---------+-------------------------------------------------------------------+
|  102  |  test4  | siku-QiTianM420-N000:9005:/curvefs/client/mnt/home/siku/temp/mnt4 |
|  101  |  test3  | siku-QiTianM420-N000:9004:/curvefs/client/mnt/home/siku/temp/mnt3 |
+-------+---------+-------------------------------------------------------------------+

curve fs list mountpoint --format json | jq
{
"error": {
"code": 0,
"message": "success"
},
"result": [
{
"fs id": "102",
"fs name": "test4",
"mount point": "siku-QiTianM420-N000:9005:/curvefs/client/mnt/home/siku/temp/mnt4"
},
{
"fs id": "101",
"fs name": "test3",
"mount point": "siku-QiTianM420-N000:9004:/curvefs/client/mnt/home/siku/temp/mnt3"
}
]
}


```

image

image

image

image

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by aspirer** [comment]
remove txOwner | txSequence from list output.

**Comment by Cyber-SiKu** [comment]
> remove txOwner | txSequence from list output.

fix

**Review by SeanHai — APPROVED** [review]

**Review by aspirer — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Pull request merged**
