### PR TITLE
[WIP] fix: fix metric may be zero

### PR DESCRIPTION
**Pull request by PerseidMeteor**
### What problem does this PR solve?

Issue Number: #2391 

# **please do not review this pr now**

Problem Summary:

### What is changed and how it works?

What's Changed:  add patch

How it Works:  we can cherry-pick some commits, which supports fork new thread without exec, to avoid metric may be zero

Side effects(Breaking backward compatibility? Performance regression?): later...

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by h0hmj** [comment]
Advice:

For readable, add your patch to existing brpc.patch is not a good idea.
Add to a new patch is better i think.
just like https://github.com/opencurve/curve/commit/b71f94469597492b4fcef590cb11e729a003ebb9

**Comment by caoxianfei1** [comment]
@PerseidMeteor continue?

**Comment by Cyber-SiKu** [comment]
@PerseidMeteor continue?

**Comment by wuhongsong** [comment]
stale, out to date. if you want to do, can reopen it.

**Pull request closed without merging**
