### PR TITLE
Remove nbd

### PR DESCRIPTION
**Pull request by cw123**
Nbd is under GPL license, curve is under apache license.
The licenses between these are conflict.
So move the nbd to a new repo.

The new nbd is at https://github.com/opencurve/curve-nbd.
This pr remove nbd dir from curve repo.

### CODE REVIEW

**Comment by cw123** [comment]
recheck

**Comment by Wine93** [comment]
have you test `make build` and `make image` after these change?

**Review by wu-hanqing — APPROVED** [review]

**Comment by cw123** [comment]
recheck

**Review by Wine93 — APPROVED** [review]
LGTM！

**Comment by cw123** [comment]
> have you test `make build` and `make image` after these change?

yes

**Pull request merged**
