### PR TITLE
[fix]curvefs/metaserver: query fsinfo once

### LINKED ISSUE #2137: [curvefs]metaserver only need to query fsinfo once when delete inode
image
image

When curvefs delete inode, metaserver will send GetFsInfo to mds per inode. There's no need to query fs info every inode every time an inode is deleted.

When deleting inode, query fs info to get s3 info. And s3 info is unchanged, only need to query once.

Affected version: master release2.3 release2.4

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
query fsinfo once when delete inode

Close #2137

Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by xu-chaojie — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Review by cw123 — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Review by cw123 — CHANGES_REQUESTED** [review]
partition_cleaner.cpp need fix too.
MetaStatusCode PartitionCleaner::CleanDataAndDeleteInode(const Inode& inode)

**Comment by Cyber-SiKu** [comment]
> partition_cleaner.cpp need fix too. MetaStatusCode PartitionCleaner::CleanDataAndDeleteInode(const Inode& inode)

done

**Review by cw123 — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
cicheck

**Pull request merged**
