### PR TITLE
curvefs/client:Fix the issue that the release version fails to compile

### LINKED ISSUE #928: unittest: ClientS3AdaptorTest.test_flush_write_more_chunk failed
pull request #775 

unittest result: http://59.111.91.248:8080/job/curve_untest_job/3147/console

### PR DESCRIPTION
**Pull request by baijiaruo**
1.Fix the issue that the release version fails to compile
2.delete unnecessary unit test cases

### What problem does this PR solve?

Issue Number: close #928  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by YunhuiChen** [comment]
recheck

**Review by wuhongsong — APPROVED** [review]

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Review by wu-hanqing — APPROVED** [review]

**Pull request merged**
