### PR TITLE
Chinese to English translation of the code comments in curve/src/chunkserver

### LINKED ISSUE #260: 【C-Plan-选题二】代码翻译
对以下板块的注释进行中文到英文的翻译
- curve/src/chunkserver

### PR DESCRIPTION
**Pull request by YechenGu**
### What problem does this PR solve?

Issue Number: close #260 

Problem Summary: Code comments in curve/src/chunkserver are in Chinese

### What is changed and how it works?

What's Changed:  Code comments in curve/src/chunkserver

How it Works: Translate them from Chinese to English

Side effects(Breaking backward compatibility? Performance regression?): 

Due to my limited level and understanding of the code, there may be inaccuracies in the translation

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Wine93** [comment]
@YechenGu The ci check is failed, please click [details](http://59.111.91.248:8080/job/opencurve_multijob/1237/) and try to fix it.

**Comment by Wine93** [comment]
recheck

**Comment by YechenGu** [comment]
> @YechenGu The ci check is failed, please click [details](http://59.111.91.248:8080/job/opencurve_multijob/1237/) and try to fix it.

Hi, thank you for notification. After a minor fix, the ci check is now successful

**Comment by ilixiaocui** [comment]
cc @YechenGu Please resubmit to the master branch if necessary.

**Pull request closed without merging**
