### PR TITLE
curvefs: change the data organization format

### PR DESCRIPTION
**Pull request by 201341**
### What problem does this PR solve?

Issue Number: #2380  

Problem Summary:
Add prefix to improve the s3 data storage sync  and write disk cache performance.

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by 201341** [comment]
cicheck

**Comment by wuhongsong** [comment]
ci failed because the disk of  ci machine is full

**Comment by wuhongsong** [comment]
cicheck

**Review by wuhongsong — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]

**Pull request merged**
