### PR TITLE
[tools] fix: get copyset status from chunkserver metric

### PR DESCRIPTION
**Pull request by caoxianfei1**
### What problem does this PR solve?

Optimize the `status copyset`, directly get all copysets from the chunkserver at once and then parse them. There is no need to call the GetCopysetStatus interface one by one to query.

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by YunhuiChen** [comment]
cicheck

**Comment by YunhuiChen** [comment]
cicheck

**Comment by YunhuiChen** [comment]
cicheck

**Comment by YunhuiChen** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Comment by caoxianfei1** [comment]
cicheck

**Review by Cyber-SiKu — APPROVED** [review]

**Review by wu-hanqing — APPROVED** [review]

**Pull request merged**
