### PR TITLE
curvefs/mds: fix create filesystem timeout

### PR DESCRIPTION
**Pull request by baijiaruo**
Signed-off-by: baijiaruo <baijiaruo@126.com>

### What problem does this PR solve?

Issue Number: #1610  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by baijiaruo** [comment]
recheck

**Review by SeanHai — APPROVED** [review]

**Comment by baijiaruo** [comment]
recheck

**Comment by baijiaruo** [comment]
recheck

**Comment by baijiaruo** [comment]
recheck

**Comment by baijiaruo** [comment]
recheck

**Review by cw123 — APPROVED** [review]

**Pull request merged**
