### PR TITLE
curvefs/client:fix datacache is release and write at the same time cause core dump

### LINKED ISSUE #716: Mismatch of an unlock is found during code review
**Describe the bug (描述bug)**
image

**To Reproduce (复现方法)**
Do not need, find this mismatch during code review.

**Expected behavior (期望行为)**
unlock correctly in all code branchs.

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by baijiaruo**
### What problem does this PR solve?

Issue Number: close #716 #715  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by ilixiaocui — APPROVED** [review]

**Review by wu-hanqing — APPROVED** [review]

**Comment by aspirer** [comment]
recheck

**Comment by aspirer** [comment]
recheck

**Comment by baijiaruo** [comment]
recheck

**Comment by baijiaruo** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Review by wu-hanqing — APPROVED** [review]

**Pull request merged**
