### PR TITLE
[refactor] CurveBS: unify bs and fs apply queue

### PR DESCRIPTION
**Pull request by Xinlong-Chen**
### What problem does this PR solve?

Issue Number: #1598 

Problem Summary:

unify bd and fs apply queue by moving schedule() to operator.

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by Xinlong-Chen** [comment]
cicheck

**Comment by wu-hanqing** [comment]
cicheck

**Comment by wu-hanqing** [comment]
cicheck

**Comment by wuhongsong** [comment]
pr stale,you can reopen it later if you want continue.

**Pull request closed without merging**
