### PR TITLE
[feat]tools-v2: bs query chunk

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

```bash
curve bs query chunk --path /test1 --offset 1008600000 
+-------+-------------+---------+------------+------------------+
| CHUNK | LOGICALPOOL | COPYSET |   GROUP    |     LOCATION     |
+-------+-------------+---------+------------+------------------+
| 61    | 1           | 61      | 4294967357 | 10.182.2.46:8301 |
|       |             |         |            | 10.182.2.46:8302 |
|       |             |         |            | 10.182.2.46:8300 |
+-------+-------------+---------+------------+------------------+
```

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by wuhongsong** [comment]
cmd output？

**Review by wu-hanqing — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
> cmd output？

fix

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by Cyber-SiKu** [comment]
cicheck

**Review by wuhongsong — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
cicheck

**Comment by Cyber-SiKu** [comment]
cicheck

**Pull request merged**
