### PR TITLE
curvebs: max/min file length support reload

### PR DESCRIPTION
**Pull request by Ziy1-Tan**
### What problem does this PR solve?

Issue Number: https://github.com/opencurve/curve/issues/2531

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Ziy1-Tan** [comment]
cicheck

**Comment by Cyber-SiKu** [comment]
Is this modification necessary?
1. The same effect should be achieved by modifying the configuration file and then restarting mds
2. Does the judgment of the code directly depend on these two flags for the judgment logic of these two values? If not, this modification will not work.

**Comment by wuhongsong** [comment]
> Is this modification necessary?
> 
> 1. The same effect should be achieved by modifying the configuration file and then restarting mds
> 2. Does the judgment of the code directly depend on these two flags for the judgment logic of these two values? If not, this modification will not work.

@Ziy1-Tan any question？

**Comment by wuhongsong** [comment]
> Is this modification necessary?
> 
> 1. The same effect should be achieved by modifying the configuration file and then restarting mds
> 2. Does the judgment of the code directly depend on these two flags for the judgment logic of these two values? If not, this modification will not work.

yep, its will not work.  @Ziy1-Tan

**Comment by Cyber-SiKu** [comment]
IMO, it need more work. @Ziy1-Tan

**Comment by Ziy1-Tan** [comment]
> IMO, it need more work. @Ziy1-Tan

ok, dynamic reloading seems to be enabled by default when defining the flag. I'm not sure what else needs to be modified.

**Comment by Cyber-SiKu** [comment]
@Ziy1-Tan You need to add some unit tests or manual tests to see if your modification takes effect, that is, whether your modification has been passed to the corresponding value.

**Comment by caoxianfei1** [comment]
@Ziy1-Tan We are temporarily closing this pull request. If you want to continue, you can reopen it.

**Pull request closed without merging**
