### PR TITLE
Shiyaoliang qos for fuse

### PR DESCRIPTION
**Pull request by YLShiJustFly**
### What problem does this PR solve?

Issue Number: https://github.com/opencurve/curve/issues/2048

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by cw123 — COMMENTED** [review]
please add some unit test

cpplint is failed. cpplint../curvefs/src/client/fuse_s3_client.h

Stacktrace
122: "private:" should be preceded by a blank line [whitespace/blank_line] [3]

**Comment by cw123** [comment]
recheck

**Comment by wuhongsong** [comment]
cpplint and  pjdtest(code compile) have some problem,  please revise it, thanks.

**Comment by ilixiaocui** [comment]
cc @YLShiJustFly  This pr has been opened for a long time, and the review comments have not been replied. Please resubmit the pr if necessary.

**Pull request closed without merging**
