### PR TITLE
curve: fix build erro in debian11

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by wu-hanqing — APPROVED** [review]

**Review by SeanHai — APPROVED** [review]

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Pull request merged**
