### PR TITLE
remove merge two inode in storage updateInode

### LINKED ISSUE #929: CI failover : After running FIO for some time, FIO is stuck, ls lh is stuck
**Describe the bug (描述bug)**
image

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by xu-chaojie**
Caution: after this commit, capaction will have error, do not open it in
config, and we will fix it later.

### What problem does this PR solve?

Issue Number: close #929  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by h0hmj** [comment]
side effect: s3compact can not be enabled until a fix.

**Review by h0hmj — APPROVED** [review]

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Review by wu-hanqing — APPROVED** [review]

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Comment by xu-chaojie** [comment]
recheck

**Review by cw123 — APPROVED** [review]

**Pull request merged**
