### PR TITLE
copyset schedule select copyset random

### PR DESCRIPTION
**Pull request by cw123**
Signed-off-by: chenwei <461432360@qq.com>

### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by cw123** [comment]
create 100 fs

topology_metric_metaserver_id_1_copyset_num 6
topology_metric_metaserver_id_2_copyset_num 6
topology_metric_metaserver_id_3_copyset_num 6
topology_metric_metaserver_id_4_copyset_num 6
topology_metric_metaserver_id_5_copyset_num 6
topology_metric_metaserver_id_6_copyset_num 6
topology_metric_metaserver_id_7_copyset_num 6
topology_metric_metaserver_id_8_copyset_num 6
topology_metric_metaserver_id_9_copyset_num 6
topology_metric_pool_pool1_copyset_num 18

topology_metric_metaserver_id_1_partition_num 401
topology_metric_metaserver_id_2_partition_num 400
topology_metric_metaserver_id_3_partition_num 399
topology_metric_metaserver_id_4_partition_num 399
topology_metric_metaserver_id_5_partition_num 401
topology_metric_metaserver_id_6_partition_num 399
topology_metric_metaserver_id_7_partition_num 400
topology_metric_metaserver_id_8_partition_num 400
topology_metric_metaserver_id_9_partition_num 401
topology_metric_pool_pool1_partition_num 1200

**Comment by cw123** [comment]
create 1000 fs
topology_metric_metaserver_id_1_partition_num 4000
topology_metric_metaserver_id_2_partition_num 3999
topology_metric_metaserver_id_3_partition_num 4001
topology_metric_metaserver_id_4_partition_num 3999
topology_metric_metaserver_id_5_partition_num 4001
topology_metric_metaserver_id_6_partition_num 3999
topology_metric_metaserver_id_7_partition_num 4000
topology_metric_metaserver_id_8_partition_num 4000
topology_metric_metaserver_id_9_partition_num 4001
topology_metric_pool_pool1_partition_num 12000


topology_metric_metaserver_id_1_copyset_num 36
topology_metric_metaserver_id_2_copyset_num 36
topology_metric_metaserver_id_3_copyset_num 36
topology_metric_metaserver_id_4_copyset_num 36
topology_metric_metaserver_id_5_copyset_num 36
topology_metric_metaserver_id_6_copyset_num 36
topology_metric_metaserver_id_7_copyset_num 36
topology_metric_metaserver_id_8_copyset_num 36
topology_metric_metaserver_id_9_copyset_num 36
topology_metric_pool_pool1_copyset_num 108

**Comment by cw123** [comment]
offline one metaserver

topology_metric_metaserver_id_1_copyset_num 36
topology_metric_metaserver_id_2_copyset_num 36
topology_metric_metaserver_id_3_copyset_num 36
topology_metric_metaserver_id_4_copyset_num 50
topology_metric_metaserver_id_5_copyset_num 58
topology_metric_metaserver_id_6_copyset_num 36
topology_metric_metaserver_id_7_copyset_num 36
topology_metric_metaserver_id_8_copyset_num 0
topology_metric_metaserver_id_9_copyset_num 36
topology_metric_pool_pool1_copyset_num 108

topology_metric_metaserver_id_1_partition_num 4000
topology_metric_metaserver_id_2_partition_num 3999
topology_metric_metaserver_id_3_partition_num 4001
topology_metric_metaserver_id_4_partition_num 5588
topology_metric_metaserver_id_5_partition_num 6412
topology_metric_metaserver_id_6_partition_num 3999
topology_metric_metaserver_id_7_partition_num 4000
topology_metric_metaserver_id_8_partition_num 0
topology_metric_metaserver_id_9_partition_num 4001
topology_metric_pool_pool1_partition_num 12000

**Comment by cw123** [comment]
start offline metaserver，wait a while

topology_metric_metaserver_id_1_copyset_num 36
topology_metric_metaserver_id_2_copyset_num 36
topology_metric_metaserver_id_3_copyset_num 36
topology_metric_metaserver_id_4_copyset_num 36
topology_metric_metaserver_id_5_copyset_num 36
topology_metric_metaserver_id_6_copyset_num 36
topology_metric_metaserver_id_7_copyset_num 36
topology_metric_metaserver_id_8_copyset_num 36
topology_metric_metaserver_id_9_copyset_num 36
topology_metric_pool_pool1_copyset_num 108

topology_metric_metaserver_id_1_partition_num 4000
topology_metric_metaserver_id_2_partition_num 3999
topology_metric_metaserver_id_3_partition_num 4001
topology_metric_metaserver_id_4_partition_num 3998
topology_metric_metaserver_id_5_partition_num 3900
topology_metric_metaserver_id_6_partition_num 3999
topology_metric_metaserver_id_7_partition_num 4000
topology_metric_metaserver_id_8_partition_num 4102
topology_metric_metaserver_id_9_partition_num 4001
topology_metric_pool_pool1_partition_num 12000

**Review by ilixiaocui — APPROVED** [review]

**Review by SeanHai — APPROVED** [review]

**Pull request merged**
