### PR TITLE
[WIP] curve bs stop volume snapshot

### PR DESCRIPTION
**Pull request by ZackSoul**
issuse number: #2579

### CODE REVIEW

**Comment by wuhongsong** [comment]
@ZackSoul  lets continue？

**Comment by ZackSoul** [comment]
I've finished writing the code but haven't tested it with local compilation yet, I'll install the local environment in the next few days and test it with compilation

**Comment by Cyber-SiKu** [comment]
You can refer to this [pr](https://github.com/opencurve/curve/pull/2713)

**Comment by ZackSoul** [comment]
Yes, my latest code is referencing this one you recommended

**Pull request closed without merging**
