### PR TITLE
nbd: close nbd fd when nbd server stopped

### PR DESCRIPTION
**Pull request by wu-hanqing**
### What problem does this PR solve?

Issue Number: close #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by wu-hanqing** [comment]
recheck

**Comment by ilixiaocui** [comment]
cc @wu-hanqing If this submission is still needed, please merge it into master as soon as possible.

**Comment by ilixiaocui** [comment]
cc @wu-hanqing  If this submission is still needed, please merge it into master as soon as possible.

**Comment by wuhongsong** [comment]
@wu-hanqing

**Pull request closed without merging**
