### PR TITLE
Curve/tool fs status etcd

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

```
curve fs status etcd
+---------------------+---------+----------+
|        addr         | version |  status  |
+---------------------+---------+----------+
| 10.219.192.50:23790 | 3.4.10  |  leader  |
| 10.219.192.50:23791 | 3.4.10  | follower |
| 10.219.192.50:23792 | 3.4.10  | follower |
+---------------------+---------+----------+
```

```

curve fs status etcd --format json | jq .
{
"error": {
"code": 0,
"message": "success"
},
"result": [
{
"addr": "10.219.192.50:23790",
"status": "leader",
"version": "3.4.10"
},
{
"addr": "10.219.192.50:23791",
"status": "follower",
"version": "3.4.10"
},
{
"addr": "10.219.192.50:23792",
"status": "follower",
"version": "3.4.10"
}
]
}
```
image
image

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by aspirer** [comment]
change StateLeader to leader, make it same to mds status output.

**Comment by Cyber-SiKu** [comment]
> change StateLeader to leader, make it same to mds status output.

fix

**Review by wu-hanqing — APPROVED** [review]

**Review by SeanHai — APPROVED** [review]

**Review by aspirer — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
recheck

**Comment by Cyber-SiKu** [comment]
recheck

**Pull request merged**
