### PR TITLE
curvefs: change getInode to getInodeAttr in readLink and recordOldInodeInfo of opRename and change dcache size to 100w

### PR DESCRIPTION
**Pull request by SeanHai**
Signed-off-by: wanghai01 <seanhaizi@163.com>

### What problem does this PR solve?

1. change the missed getInode to getInodeAttr.
2. change the dcache size to 100w to improve performance. The max size of 100w dentry is about 540MB and just about 100MB under normal circumstances.
截屏2022-08-19 15 59 17

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by SeanHai** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Comment by SeanHai** [comment]
recheck

**Review by Wine93 — APPROVED** [review]
LGTM!

**Pull request merged**
