### PR TITLE
Curve/tool fs delete fs

### PR DESCRIPTION
**Pull request by Cyber-SiKu**
### What problem does this PR solve?

Issue Number: #xxx 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

```
curve fs delete fs --fsname test3
WARNING: After deleting fs, the data cannot be retrieved!!
input [test3] to confirm: test3
+---------+---------+
| fs name | result  |
+---------+---------+
|  test3  | success |
+---------+---------+

curve fs delete fs --fsname test -f json
WARNING: After deleting fs, the data cannot be retrieved!!
input [test] to confirm: test
{
"error": {
"code": 0,
"message": "success"
},
"result": {
"statusCode": "OK"
}
}

```
image
image

Side effects(Breaking backward compatibility? Performance regression?):

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by aspirer** [comment]
change the prompt message when deleting fs.

**Comment by Cyber-SiKu** [comment]
> change the prompt message when deleting fs.

fxi

**Comment by SeanHai** [comment]
The confirm input is 'yes/no' is better.

**Review by wu-hanqing — APPROVED** [review]

**Comment by Cyber-SiKu** [comment]
> The confirm input is 'yes/no' is better.

enter fsname to prevent accidental deletion of other fs

**Review by SeanHai — APPROVED** [review]

**Pull request merged**
